#!/bin/bash
# Bluetrade AI — Git deploy script
# Generated by Claude. Run once to push to GitHub.

set -e
cd "/Users/brandtmaples/Desktop/Bluetrade AI/Bluetrade AI"

echo "========================================="
echo "  Bluetrade AI — GitHub Deploy Script"
echo "========================================="
echo ""

# 1. Remove any stale git lock file
rm -f .git/index.lock
echo "✓ Cleared any stale git locks"

# 2. Stage all files (respecting .gitignore)
git add .
echo "✓ Staged all project files"

# 3. Commit
git commit -m "Initial commit — deploy to Vercel"
echo "✓ Committed"

# 4. Add remote (skip if already set)
if ! git remote get-url origin &>/dev/null; then
  git remote add origin https://github.com/Bluetradeai/Blue-Trade-Ai-Website.git
  echo "✓ Remote origin added"
else
  echo "✓ Remote origin already set: $(git remote get-url origin)"
fi

# 5. Push to GitHub
echo ""
echo "Pushing to GitHub..."
git push -u origin main

echo ""
echo "========================================="
echo "  ✅ DONE! All files pushed to GitHub."
echo "  Vercel will auto-deploy shortly."
echo "========================================="
